-- SnapNest Dispatch schema entry point.
-- v0.2 moved the production schema into a real migration so Supabase can track it cleanly.
-- Canonical schema: database/migrations/0001_dispatch_v0_2.sql
-- Development seed: database/seed.sql
